AWSTemplateFormatVersion: '2010-09-09'
Description: Security groups for AIOps components
Parameters:
  VPCID:
    Type: String
    Description: VPC ID where the SG will be created
Resources:
  PublicSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Public SG for AIOps services
      VpcId: !Ref VPCID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
Outputs:
  PublicSG:
    Value: !Ref PublicSG
